version: '3'
services:
  web:
    container_name: web
    image: nginx:1.13.12-alpine
    volumes:
      - ./nginx/mysite.template:/etc/nginx/conf.d/mysite.template
      - ./res:/usr/share/nginx/slides/res:ro
      - ./dist:/usr/share/nginx/slides/dist:ro
    ports:
      - '8888:80'
    environment:
      - NGINX_PORT=80
      - NGINX_ROOT=/usr/share/nginx
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  slides:
    container_name: slides
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/slides
      - /slides/node_modules/
    ports:
      - '8889:80'
    working_dir: /slides
    #command: /bin/sh -c "npm i && npm start"
    command: /bin/sh -c "npm i && npm run build"
